version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: jenmoney
      POSTGRES_USER: jenmoney
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jenmoney -d jenmoney"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      JENMONEY_DATABASE_URL: postgresql://jenmoney:password123@postgres:5432/jenmoney
      JENMONEY_ENVIRONMENT: development
      JENMONEY_DEBUG: "true"
      JENMONEY_CORS_ORIGINS: '["http://localhost:3000", "http://localhost:5173", "http://localhost"]'
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: