name: Setup Development Environment for GitHub Copilot

on:
  workflow_dispatch:
  
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    name: Setup development environment with uv, Node.js, and dev tools
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Install a specific version
          version: "0.5.18"
          
      - name: Set up Python
        run: uv python install 3.13
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            wget \
            sqlite3 \
            lsof
            
      - name: Install backend Python dependencies
        working-directory: ./backend
        run: |
          uv sync --dev
          
      - name: Install frontend Node.js dependencies
        working-directory: ./frontend
        run: |
          npm ci
          
      - name: Install pre-commit hooks
        working-directory: ./backend
        run: |
          uv run pre-commit install
          
      - name: Verify installations
        run: |
          echo "=== UV Installation ==="
          uv --version
          echo "=== Python Installation ==="
          uv python list
          echo "=== Node.js Installation ==="
          node --version
          npm --version
          echo "=== Backend Dependencies ==="
          cd backend && uv pip list
          echo "=== Frontend Dependencies ==="
          cd frontend && npm list --depth=0
          echo "=== Development Tools ==="
          cd backend && uv run ruff --version
          cd backend && uv run mypy --version
          cd backend && uv run pytest --version
          echo "=== Pre-commit ==="
          cd backend && uv run pre-commit --version
          
      - name: Initialize database
        working-directory: ./backend
        run: |
          mkdir -p data
          uv run python -c "
          from jenmoney.database import init_db
          init_db()
          print('Database initialized successfully')
          "
          
      - name: Run quick smoke tests
        run: |
          echo "=== Backend Tests ==="
          cd backend && uv run pytest --tb=short -q
          echo "=== Frontend Build Test ==="
          cd frontend && npm run build
          echo "=== Linting Tests ==="
          cd backend && uv run ruff check src/
          cd backend && uv run mypy src/
          
      - name: Display environment summary
        run: |
          echo "🎉 Development environment setup complete!"
          echo ""
          echo "Available tools:"
          echo "- Python: $(uv python list | grep '3.13' | head -1)"
          echo "- uv: $(uv --version)"
          echo "- Node.js: $(node --version)"
          echo "- npm: $(npm --version)"
          echo ""
          echo "Available commands:"
          echo "- make setup     # Complete project setup"
          echo "- make dev       # Start development servers"
          echo "- make test      # Run backend tests"
          echo "- make lint      # Run code linting"
          echo "- make format    # Format code"
          echo "- make typecheck # Run type checking"
          echo ""
          echo "Backend directory: ./backend"
          echo "Frontend directory: ./frontend"
          echo "Database file: ./backend/data/finance.db"